#!/bin/bash

sudo apt-get install libgtk-3-dev libpython3.9-dev

pip uninstall wxPython
pip install --force-reinstall --no-clean --no-cache-dir -vvv wxPython

wxpython_build_path=$(find /tmp -name "wxpython*")
if [ "_${wxpython_build_path}" == "_" ]
then
	echo "wxPython not found in /tmp"
	exit 1
fi
wxpython_install_path=$(python patch/wxPython_path.py)
if [ "_${wxpython_install_path}" == "_" ]
then
	echo "wxPython not installed"
	exit 1
fi

echo "build path:   $wxpython_build_path"
echo "install path: $wxpython_install_path"

echo "patch file $wxpython_build_path/ext/wxWidgets/src/gtk/dataview.cpp"
# cat patch/dataview.cpp.74e1c44 > $wxpython_build_path/ext/wxWidgets/src/gtk/dataview.cpp
# cat patch/dataview.h.74e1c44 > $wxpython_build_path/ext/wxWidgets/include/wx/dataview.h
patch $wxpython_build_path/ext/wxWidgets/src/gtk/dataview.cpp patch/dataview.c.patch

echo "rebuild $wxpython_build_path"
cd $wxpython_build_path
python build.py build
cp -vf ./wx/libwx_gtk3u_core-3.1.so.5.0.0 ${wxpython_install_path}/

echo cleanup
#rm -rf $wxpython_build_path

