swagger: "2.0"
info:
  version: 1.0.0
  title: Kipartman
  description: Kipartman api specifications
  termsOfService: http://swagger.io/terms/
  contact:
    name: Sebastien Besombes
    email: --
    url: https://github.com/turdusmerula/kipartman
  license:
    name: GPL V3
    url: https://raw.githubusercontent.com/turdusmerula/kipartman/master/LICENSE
host: localhost:8200
#host: kipartman.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /parts/categories:
    $ref: './part/category/categories.yaml'
    
  /parts/category/{category_id}:
    $ref: './part/category/category.yaml'

  /parts:
    $ref: './part/parts.yaml'

  /part/{part_id}:
    $ref: './part/part.yaml'

  /parts/parameters:
    $ref: './part/parameter/parameters.yaml'


  /units:    
    $ref: './unit/units.yaml'

  /unit/{unit_id}:    
    $ref: './unit/unit.yaml'

  /unitprefixes:    
    $ref: './unit/unitprefixes.yaml'

  /unitprefix/{unit_prefix_id}:    
    $ref: './unit/unitprefix.yaml'



  /distributors:
    $ref: './distributor/distributors.yaml'
            
  /distributor/{distributor_id}:
    $ref: './distributor/distributor.yaml'

            

  /manufacturers:
    $ref: './manufacturer/manufacturers.yaml'
            
  /manufacturer/{manufacturer_id}:
    $ref: './manufacturer/manufacturer.yaml'


  /upload:
    $ref: './upload/upload.yaml'

  /version/synchronize:
    $ref: './version/synchronize.yaml'

  /version/commit:
    $ref: './version/commit.yaml'

  /version/update:
    $ref: './version/update.yaml'


  /storages/categories:
    $ref: './storage/category/categories.yaml'
    
  /storages/category/{category_id}:
    $ref: './storage/category/category.yaml'

  /storages:
    $ref: './storage/storages.yaml'

  /storage/{storage_id}:
    $ref: './storage/storage.yaml'


  /currencies:
    $ref: './currency/currencies.yaml'

  /date:
    $ref: './date/date.yaml'
    