# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='footprint',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Footprint'),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.FootprintCategory'),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
