# coding: utf-8

from __future__ import absolute_import

from swagger_server.models.footprint_category_data import FootprintCategoryData
from swagger_server.models.footprint_category_ref import FootprintCategoryRef
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class FootprintCategory(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=None, id=None, parent=None, childs=None):
        """
        FootprintCategory - a model defined in Swagger

        :param name: The name of this FootprintCategory.
        :type name: str
        :param id: The id of this FootprintCategory.
        :type id: int
        :param parent: The parent of this FootprintCategory.
        :type parent: FootprintCategoryRef
        :param childs: The childs of this FootprintCategory.
        :type childs: List[FootprintCategory]
        """
        self.swagger_types = {
            'name': str,
            'id': int,
            'parent': FootprintCategoryRef,
            'childs': List[FootprintCategory]
        }

        self.attribute_map = {
            'name': 'name',
            'id': 'id',
            'parent': 'parent',
            'childs': 'childs'
        }

        self._name = name
        self._id = id
        self._parent = parent
        self._childs = childs

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FootprintCategory of this FootprintCategory.
        :rtype: FootprintCategory
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self):
        """
        Gets the name of this FootprintCategory.

        :return: The name of this FootprintCategory.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this FootprintCategory.

        :param name: The name of this FootprintCategory.
        :type name: str
        """

        self._name = name

    @property
    def id(self):
        """
        Gets the id of this FootprintCategory.

        :return: The id of this FootprintCategory.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this FootprintCategory.

        :param id: The id of this FootprintCategory.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def parent(self):
        """
        Gets the parent of this FootprintCategory.

        :return: The parent of this FootprintCategory.
        :rtype: FootprintCategoryRef
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """
        Sets the parent of this FootprintCategory.

        :param parent: The parent of this FootprintCategory.
        :type parent: FootprintCategoryRef
        """

        self._parent = parent

    @property
    def childs(self):
        """
        Gets the childs of this FootprintCategory.

        :return: The childs of this FootprintCategory.
        :rtype: List[FootprintCategory]
        """
        return self._childs

    @childs.setter
    def childs(self, childs):
        """
        Sets the childs of this FootprintCategory.

        :param childs: The childs of this FootprintCategory.
        :type childs: List[FootprintCategory]
        """

        self._childs = childs

