# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.part_category_data import PartCategoryData

from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class PartCategoryTree(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=None, id=None, parent=None):
        """
        PartCategoryTree - a model defined in Swagger

        :param name: The name of this PartCategoryTree.
        :type name: str
        :param id: The id of this PartCategoryTree.
        :type id: int
        :param parent: The parent of this PartCategoryTree.
        :type parent: PartCategoryTree
        """
        self.swagger_types = {
            'name': str,
            'id': int,
            'parent': PartCategoryTree
        }

        self.attribute_map = {
            'name': 'name',
            'id': 'id',
            'parent': 'parent'
        }

        self._name = name
        self._id = id
        self._parent = parent

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PartCategoryTree of this PartCategoryTree.
        :rtype: PartCategoryTree
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self):
        """
        Gets the name of this PartCategoryTree.

        :return: The name of this PartCategoryTree.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this PartCategoryTree.

        :param name: The name of this PartCategoryTree.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def id(self):
        """
        Gets the id of this PartCategoryTree.

        :return: The id of this PartCategoryTree.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this PartCategoryTree.

        :param id: The id of this PartCategoryTree.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def parent(self):
        """
        Gets the parent of this PartCategoryTree.

        :return: The parent of this PartCategoryTree.
        :rtype: PartCategoryTree
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """
        Sets the parent of this PartCategoryTree.

        :param parent: The parent of this PartCategoryTree.
        :type parent: PartCategoryTree
        """

        self._parent = parent

