# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.storage_category_data import StorageCategoryData
from swagger_server.models.storage_category_ref import StorageCategoryRef
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class StorageCategoryNew(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=None, description=None, parent=None):
        """
        StorageCategoryNew - a model defined in Swagger

        :param name: The name of this StorageCategoryNew.
        :type name: str
        :param description: The description of this StorageCategoryNew.
        :type description: str
        :param parent: The parent of this StorageCategoryNew.
        :type parent: StorageCategoryRef
        """
        self.swagger_types = {
            'name': str,
            'description': str,
            'parent': StorageCategoryRef
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'parent': 'parent'
        }

        self._name = name
        self._description = description
        self._parent = parent

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StorageCategoryNew of this StorageCategoryNew.
        :rtype: StorageCategoryNew
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self):
        """
        Gets the name of this StorageCategoryNew.

        :return: The name of this StorageCategoryNew.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this StorageCategoryNew.

        :param name: The name of this StorageCategoryNew.
        :type name: str
        """

        self._name = name

    @property
    def description(self):
        """
        Gets the description of this StorageCategoryNew.

        :return: The description of this StorageCategoryNew.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this StorageCategoryNew.

        :param description: The description of this StorageCategoryNew.
        :type description: str
        """

        self._description = description

    @property
    def parent(self):
        """
        Gets the parent of this StorageCategoryNew.

        :return: The parent of this StorageCategoryNew.
        :rtype: StorageCategoryRef
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """
        Sets the parent of this StorageCategoryNew.

        :param parent: The parent of this StorageCategoryNew.
        :type parent: StorageCategoryRef
        """

        self._parent = parent

