# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.symbol_data import SymbolData
from swagger_server.models.versioned_file import VersionedFile
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Symbol(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=None, description=None, comment=None, snapeda=None, snapeda_uid=None, updated=None, id=None, symbol=None):
        """
        Symbol - a model defined in Swagger

        :param name: The name of this Symbol.
        :type name: str
        :param description: The description of this Symbol.
        :type description: str
        :param comment: The comment of this Symbol.
        :type comment: str
        :param snapeda: The snapeda of this Symbol.
        :type snapeda: str
        :param snapeda_uid: The snapeda_uid of this Symbol.
        :type snapeda_uid: str
        :param updated: The updated of this Symbol.
        :type updated: datetime
        :param id: The id of this Symbol.
        :type id: int
        :param symbol: The symbol of this Symbol.
        :type symbol: VersionedFile
        """
        self.swagger_types = {
            'name': str,
            'description': str,
            'comment': str,
            'snapeda': str,
            'snapeda_uid': str,
            'updated': datetime,
            'id': int,
            'symbol': VersionedFile
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'comment': 'comment',
            'snapeda': 'snapeda',
            'snapeda_uid': 'snapeda_uid',
            'updated': 'updated',
            'id': 'id',
            'symbol': 'symbol'
        }

        self._name = name
        self._description = description
        self._comment = comment
        self._snapeda = snapeda
        self._snapeda_uid = snapeda_uid
        self._updated = updated
        self._id = id
        self._symbol = symbol

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Symbol of this Symbol.
        :rtype: Symbol
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self):
        """
        Gets the name of this Symbol.

        :return: The name of this Symbol.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Symbol.

        :param name: The name of this Symbol.
        :type name: str
        """

        self._name = name

    @property
    def description(self):
        """
        Gets the description of this Symbol.

        :return: The description of this Symbol.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this Symbol.

        :param description: The description of this Symbol.
        :type description: str
        """

        self._description = description

    @property
    def comment(self):
        """
        Gets the comment of this Symbol.

        :return: The comment of this Symbol.
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """
        Sets the comment of this Symbol.

        :param comment: The comment of this Symbol.
        :type comment: str
        """

        self._comment = comment

    @property
    def snapeda(self):
        """
        Gets the snapeda of this Symbol.

        :return: The snapeda of this Symbol.
        :rtype: str
        """
        return self._snapeda

    @snapeda.setter
    def snapeda(self, snapeda):
        """
        Sets the snapeda of this Symbol.

        :param snapeda: The snapeda of this Symbol.
        :type snapeda: str
        """

        self._snapeda = snapeda

    @property
    def snapeda_uid(self):
        """
        Gets the snapeda_uid of this Symbol.

        :return: The snapeda_uid of this Symbol.
        :rtype: str
        """
        return self._snapeda_uid

    @snapeda_uid.setter
    def snapeda_uid(self, snapeda_uid):
        """
        Sets the snapeda_uid of this Symbol.

        :param snapeda_uid: The snapeda_uid of this Symbol.
        :type snapeda_uid: str
        """

        self._snapeda_uid = snapeda_uid

    @property
    def updated(self):
        """
        Gets the updated of this Symbol.

        :return: The updated of this Symbol.
        :rtype: datetime
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """
        Sets the updated of this Symbol.

        :param updated: The updated of this Symbol.
        :type updated: datetime
        """

        self._updated = updated

    @property
    def id(self):
        """
        Gets the id of this Symbol.

        :return: The id of this Symbol.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Symbol.

        :param id: The id of this Symbol.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def symbol(self):
        """
        Gets the symbol of this Symbol.

        :return: The symbol of this Symbol.
        :rtype: VersionedFile
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol):
        """
        Sets the symbol of this Symbol.

        :param symbol: The symbol of this Symbol.
        :type symbol: VersionedFile
        """

        self._symbol = symbol

