# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class UnitData(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=None, symbol=None):
        """
        UnitData - a model defined in Swagger

        :param name: The name of this UnitData.
        :type name: str
        :param symbol: The symbol of this UnitData.
        :type symbol: str
        """
        self.swagger_types = {
            'name': str,
            'symbol': str
        }

        self.attribute_map = {
            'name': 'name',
            'symbol': 'symbol'
        }

        self._name = name
        self._symbol = symbol

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UnitData of this UnitData.
        :rtype: UnitData
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self):
        """
        Gets the name of this UnitData.

        :return: The name of this UnitData.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this UnitData.

        :param name: The name of this UnitData.
        :type name: str
        """

        self._name = name

    @property
    def symbol(self):
        """
        Gets the symbol of this UnitData.

        :return: The symbol of this UnitData.
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol):
        """
        Sets the symbol of this UnitData.

        :param symbol: The symbol of this UnitData.
        :type symbol: str
        """

        self._symbol = symbol

