# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170605_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partdistributor',
            old_name='item_price',
            new_name='unit_price',
        ),
    ]
