# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-11 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170605_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='footprint',
            name='image',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
