# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170611_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footprint',
            name='footprint',
            field=models.FileField(null=True, upload_to='footprints'),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%m/%d'),
        ),
    ]
