# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_footprint_snapeda'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='email',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='phone',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='website',
            field=models.TextField(blank=True, default=''),
        ),
    ]
