# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-02 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20170627_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='partdistributor',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
