# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20170709_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footprint',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
