# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20170710_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='partoffer',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
