# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-19 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20170819_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='description',
        ),
        migrations.AddField(
            model_name='partattachement',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
