# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-24 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.TextField()),
                ('storage_path', models.TextField()),
                ('md5', models.TextField(blank=True, default='')),
                ('updated', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VersionedFileHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.TextField()),
                ('md5', models.TextField(blank=True, default='')),
                ('operation', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=None, null=True)),
                ('file', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.VersionedFile')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='created',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
