# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-27 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20171224_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionedfilehistory',
            name='date',
        ),
        migrations.AddField(
            model_name='versionedfile',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='versionedfile',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='versionedfilehistory',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='versionedfilehistory',
            name='storage_path',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='versionedfilehistory',
            name='updated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='versionedfilehistory',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='versionedfile',
            name='storage_path',
            field=models.TextField(default=''),
        ),
    ]
