# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-10 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20180429_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='partoffer',
            name='available_stock',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='partoffer',
            name='min_order_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='partoffer',
            name='packaging',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partoffer',
            name='packaging_unit',
            field=models.IntegerField(default=1),
        ),
    ]
