# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-23 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_partparameter_from_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='partreference',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
