# Generated by Django 2.1.7 on 2019-02-25 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20190122_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partattachement',
            name='part',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attachements', to='api.Part'),
        ),
        migrations.AlterField(
            model_name='partmanufacturer',
            name='part',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='api.Part'),
        ),
        migrations.AlterField(
            model_name='partoffer',
            name='part',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api.Part'),
        ),
        migrations.AlterField(
            model_name='partparameter',
            name='part',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='api.Part'),
        ),
        migrations.AlterField(
            model_name='partreference',
            name='part',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='api.Part'),
        ),
        migrations.AlterField(
            model_name='partstorage',
            name='part',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='api.Part'),
        ),
        migrations.AlterField(
            model_name='partstoragehistory',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Storage'),
        ),
        migrations.AlterField(
            model_name='partstoragehistory',
            name='part',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Part'),
        ),
        migrations.AlterField(
            model_name='versionedfilehistory',
            name='file',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.VersionedFile'),
        ),
    ]
