# Generated by Django 3.1 on 2020-09-03 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20200831_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('numeric', models.BooleanField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.unit')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='alias', to='api.parameter')),
            ],
        ),
        migrations.AddField(
            model_name='partparameter',
            name='parameter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parameter', to='api.parameter'),
        ),
    ]
