# Generated by Django 3.1 on 2020-09-03 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_migrate_part_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partparameter',
            name='description',
        ),
        migrations.RemoveField(
            model_name='partparameter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='partparameter',
            name='numeric',
        ),
        migrations.RemoveField(
            model_name='partparameter',
            name='unit',
        ),
    ]
