# Generated by Django 3.1 on 2020-09-07 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20200903_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partparameter',
            name='parameter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parameter', to='api.parameter'),
            preserve_default=False,
        ),
    ]
