# Generated by Django 3.1 on 2020-09-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_library_librarysymbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarysymbol',
            name='metadata',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
