# Generated by Django 3.1 on 2020-09-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_librarysymbol_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarysymbol',
            name='mtime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
