# Generated by Django 3.1 on 2020-09-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_librarysymbol_mtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarysymbol',
            name='mtime',
            field=models.FloatField(),
        ),
    ]
