# Generated by Django 3.1 on 2020-09-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20200911_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarysymbol',
            name='mtime',
        ),
        migrations.AddField(
            model_name='library',
            name='mtime',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
