# Generated by Django 3.1 on 2020-09-13 20:13

from django.db import migrations, models
import django.db.models.deletion
import os

def migrate_symbols(apps, schema_editor):
    Part = apps.get_model("api", "Part")
    LibrarySymbol = apps.get_model("api", "LibrarySymbol")

    for part in Part.objects.all():
        print("-", part.name)
        if part.symbol is not None:
#             if part.symbol.source_path
            symbol = None
            for s in LibrarySymbol.objects.all():
                if part.symbol.source_path==os.path.join(s.library.path, s.name+".mod"):
                    symbol = s
            if s is None:
                print(f"no match found for symbol {part.symbol.source_path}")
            part.newsymbol = symbol
            part.save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20200912_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='newsymbol',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='symbol', to='api.librarysymbol'),
        ),
        migrations.RunPython(migrate_symbols)
    ]
