# Generated by Django 3.1 on 2020-09-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_part_newsymbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='symbol',
        ),
    ]
