# Generated by Django 3.1 on 2020-09-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_remove_part_symbol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='newsymbol',
            new_name='symbol',
        ),
    ]
