# Generated by Django 3.1 on 2020-09-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_kicadfootprint_kicadfootprintlibrary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kicadfootprintlibrary',
            name='mtime_lib',
        ),
        migrations.AddField(
            model_name='kicadfootprint',
            name='mtime',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
