# Generated by Django 3.1 on 2020-09-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_remove_part_footprint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='new_footprint',
            new_name='footprint',
        ),
    ]
