# Generated by Django 3.1 on 2020-09-26 21:43

from django.db import migrations, models

def migrate_part_value(apps, schema_editor):
    Part = apps.get_model("api", "Part")

    for part in Part.objects.all():
        print("-", part.name)
        if part.value_parameter is None or part.value_parameter=="":
            part.value = "{name}"
        else:
            part.value = "{"+part.value_parameter+"}"
        part.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_auto_20200922_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='value',
            field=models.TextField(blank=True, default='{name}'),
        ),
        migrations.RunPython(migrate_part_value)
    ]
