# Generated by Django 3.1 on 2020-09-26 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_part_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='value_parameter',
        ),
    ]
