# Generated by Django 3.1 on 2020-09-27 08:07

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_remove_part_value_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='value',
            field=api.models.PartValueField(blank=True, default='{name}'),
        ),
    ]
