# Generated by Django 3.1 on 2020-10-13 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_auto_20200927_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partparameter',
            old_name='nom_value',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='partparameter',
            name='max_prefix',
        ),
        migrations.RemoveField(
            model_name='partparameter',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='partparameter',
            name='min_prefix',
        ),
        migrations.RemoveField(
            model_name='partparameter',
            name='min_value',
        ),
        migrations.RemoveField(
            model_name='partparameter',
            name='nom_prefix',
        ),
        migrations.AddField(
            model_name='parameter',
            name='percent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partparameter',
            name='prefix',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='min', to='api.unitprefix'),
        ),
    ]
