# Generated by Django 3.1 on 2020-10-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_auto_20201013_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='percent',
        ),
        migrations.AddField(
            model_name='unit',
            name='prefixable',
            field=models.BooleanField(default=True),
        ),
    ]
