# Generated by Django 3.1 on 2020-10-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_auto_20201013_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameteralias',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameteralias',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
