# Generated by Django 3.1 on 2020-10-14 22:33

import api.models
from django.db import migrations, models

def migrate_value_type(apps, schema_editor):
    Parameter = apps.get_model("api", "Parameter")

    for parameter in Parameter.objects.all():
        print("-", parameter.name)
        if parameter.numeric==True:
            parameter.value_type = "float"
        else:
            parameter.value_type = "text"
            
        parameter.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_auto_20201014_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='value_type',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_value_type)
    ]

