# Generated by Django 3.1 on 2020-10-14 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_parameter_value_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='numeric',
        ),
    ]
