# Generated by Django 3.1 on 2020-10-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_remove_parameter_numeric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='value_type',
            field=models.TextField(),
        ),
    ]
