# Generated by Django 3.1 on 2020-10-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_auto_20201014_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='metapart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partparameter',
            name='metaparameter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partparameter',
            name='operator',
            field=models.TextField(default=None, null=True),
        ),
    ]
