# Generated by Django 3.1.2 on 2020-11-06 11:56

import database.models
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('symbol', models.TextField(default='')),
                ('base', models.TextField(default='EUR')),
                ('ratio', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('website', models.TextField(blank=True, default='', null=True)),
                ('sku_url', models.TextField(blank=True, default='', null=True)),
                ('email', models.TextField(blank=True, default='', null=True)),
                ('phone', models.TextField(blank=True, default='', null=True)),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('allowed', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.TextField()),
                ('storage_path', models.TextField()),
                ('created', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KicadFootprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('content', models.TextField()),
                ('mtime', models.FloatField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KicadFootprintLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(blank=True, default='')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KicadSymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('content', models.TextField()),
                ('metadata', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KicadSymbolLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(blank=True, default='')),
                ('mtime_lib', models.FloatField()),
                ('mtime_dcm', models.FloatField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('website', models.TextField(blank=True, default='', null=True)),
                ('email', models.TextField(blank=True, default='', null=True)),
                ('phone', models.TextField(blank=True, default='', null=True)),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('value_type', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('comment', models.TextField(blank=True, default='')),
                ('value', database.models.PartValueField(blank=True, default='{name}')),
                ('metapart', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('symbol', models.TextField(default='')),
                ('prefixable', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitPrefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('symbol', models.TextField()),
                ('power', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VersionedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.TextField()),
                ('storage_path', models.TextField(default='')),
                ('md5', models.TextField(blank=True, default='')),
                ('version', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('metadata', models.TextField(blank=True, default='', null=True)),
                ('category', models.TextField(blank=True, default='', null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VersionedFileHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.TextField()),
                ('storage_path', models.TextField(default='')),
                ('md5', models.TextField(blank=True, default='')),
                ('version', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('operation', models.TextField()),
                ('file', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.versionedfile')),
            ],
        ),
        migrations.CreateModel(
            name='StorageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.storagecategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('comment', models.TextField(blank=True, default='')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.storagecategory')),
            ],
        ),
        migrations.CreateModel(
            name='PartStorageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('amount', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.storage')),
                ('part', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.part')),
            ],
        ),
        migrations.CreateModel(
            name='PartStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='database.part')),
                ('storage', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.storage')),
            ],
        ),
        migrations.CreateModel(
            name='PartReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('manufacturer', models.TextField(blank=True, default='')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('uid', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='database.part')),
            ],
        ),
        migrations.CreateModel(
            name='PartParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(null=True)),
                ('metaparameter', models.BooleanField(default=False)),
                ('operator', models.TextField(default=None, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parameter', to='database.parameter')),
                ('part', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='database.part')),
                ('prefix', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='min', to='database.unitprefix')),
            ],
        ),
        migrations.CreateModel(
            name='PartOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_unit', models.IntegerField(default=1)),
                ('min_order_quantity', models.IntegerField(default=1)),
                ('quantity', models.IntegerField()),
                ('available_stock', models.IntegerField(blank=True, default=None, null=True)),
                ('unit_price', models.FloatField()),
                ('packaging', models.TextField(blank=True)),
                ('currency', models.TextField(blank=True)),
                ('sku', models.TextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.distributor')),
                ('part', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='database.part')),
            ],
        ),
        migrations.CreateModel(
            name='PartManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.manufacturer')),
                ('part', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='database.part')),
            ],
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.partcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartAttachement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.file')),
                ('part', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attachements', to='database.part')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.partcategory'),
        ),
        migrations.AddField(
            model_name='part',
            name='childs',
            field=models.ManyToManyField(blank=True, to='database.Part'),
        ),
        migrations.AddField(
            model_name='part',
            name='footprint',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='new_footprint', to='database.kicadfootprint'),
        ),
        migrations.AddField(
            model_name='part',
            name='symbol',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='symbol', to='database.kicadsymbol'),
        ),
        migrations.CreateModel(
            name='ParameterAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='alias', to='database.parameter')),
            ],
        ),
        migrations.AddField(
            model_name='parameter',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.unit'),
        ),
        migrations.AddField(
            model_name='kicadsymbol',
            name='library',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='database.kicadsymbollibrary'),
        ),
        migrations.AddField(
            model_name='kicadfootprint',
            name='library',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='footprints', to='database.kicadfootprintlibrary'),
        ),
    ]
