# Generated by Django 3.1.2 on 2020-11-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='childs',
        ),
    ]
