# Generated by Django 4.0 on 2022-01-02 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_currency_id_alter_distributor_id_alter_file_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parts', to='database.partcategory'),
        ),
    ]
