# Generated by Django 4.0 on 2022-01-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_part_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.JSONField(),
        ),
    ]
