# Generated by Django 4.0 on 2022-01-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_parameter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partparameter',
            name='prefix',
        ),
        migrations.AddField(
            model_name='partparameter',
            name='unit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='unit',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='ParameterAlias',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.DeleteModel(
            name='UnitPrefix',
        ),
    ]
