# Generated by Django 4.0 on 2022-01-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_parameter_value_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partparameter',
            old_name='value',
            new_name='float_value',
        ),
        migrations.AddField(
            model_name='partparameter',
            name='int_value',
            field=models.IntegerField(null=True),
        ),
    ]
