# Generated by Django 4.0 on 2022-02-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_partparameter_boolean_value_partparameter_list_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='instance',
            field=models.TextField(choices=[('part', 'Part'), ('metapart', 'Metapart'), ('octopart', 'Octopart')], default='part', null=True),
        ),
        migrations.AlterField(
            model_name='partparameter',
            name='operator',
            field=models.TextField(choices=[('=', 'Eq'), ('!=', 'Ne'), ('>', 'Gt'), ('>=', 'Ge'), ('<', 'Mt'), ('<=', 'Me')], default='=', null=True),
        ),
    ]
