# Generated by Django 4.0 on 2022-02-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_parameter_findchips_parameter_octopart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
