# Generated by Django 4.0 on 2022-02-06 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_parameter_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='findchips',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='octopart',
        ),
    ]
