# Generated by Django 4.0 on 2022-02-06 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_remove_parameter_findchips_remove_parameter_octopart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partparameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='part_parameters', to='database.parameter'),
        ),
    ]
