# Generated by Django 4.0 on 2022-02-07 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_alter_partparameter_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partparameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_parameters', to='database.parameter'),
        ),
    ]
