# Generated by Django 4.0 on 2022-02-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_alter_partparameter_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='model3d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='footprint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='symbol',
            field=models.TextField(blank=True, null=True),
        ),
    ]
