# Generated by Django 4.0 on 2022-02-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_part_model3d_alter_part_footprint_alter_part_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kicadsymbol',
            name='library',
        ),
        migrations.DeleteModel(
            name='KicadFootprint',
        ),
        migrations.DeleteModel(
            name='KicadFootprintLibrary',
        ),
        migrations.DeleteModel(
            name='KicadSymbol',
        ),
        migrations.DeleteModel(
            name='KicadSymbolLibrary',
        ),
    ]
