# Generated by Django 4.0 on 2022-02-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_remove_kicadsymbol_library_delete_kicadfootprint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partparameter',
            name='boolean_value',
        ),
        migrations.RemoveField(
            model_name='partparameter',
            name='float_value',
        ),
        migrations.RemoveField(
            model_name='partparameter',
            name='int_value',
        ),
        migrations.RemoveField(
            model_name='partparameter',
            name='list_value',
        ),
        migrations.RemoveField(
            model_name='partparameter',
            name='text_value',
        ),
    ]
