# Generated by Django 4.0 on 2022-02-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_remove_partparameter_boolean_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partparameter',
            name='unit',
        ),
    ]
