# Generated by Django 4.0 on 2022-02-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_remove_partparameter_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='partparameter',
            name='value',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
