# Generated by Django 4.0 on 2022-02-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_partparameter_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='value_type',
            field=models.TextField(choices=[('integer', 'Integer'), ('float', 'Float'), ('text', 'Text')], default='float'),
        ),
        migrations.AlterField(
            model_name='partparameter',
            name='operator',
            field=models.TextField(choices=[('=', 'Eq'), ('x, y', 'Range'), ('x, y, z', 'Anyof')], default='=', null=True),
        ),
    ]
