# Generated by Django 4.0 on 2022-02-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_alter_parameter_value_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partparameter',
            name='operator',
            field=models.TextField(choices=[('=', 'Eq'), ('x, y', 'Range'), ('x, y, z', 'Anyof')], default=None, null=True),
        ),
    ]
