# Generated by Django 4.0 on 2022-03-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_alter_partparameter_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partparameter',
            name='operator',
            field=models.TextField(choices=[('=', 'Eq'), ('range', 'Range')], default=None, null=True),
        ),
    ]
