# Generated by Django 4.0 on 2022-05-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_alter_partparameter_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='category',
        ),
        migrations.DeleteModel(
            name='StorageCategory',
        ),
    ]
