# Generated by Django 4.0 on 2022-05-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_remove_storage_category_delete_storagecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='comment',
        ),
    ]
