# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footprint',
            name='level',
        ),
        migrations.RemoveField(
            model_name='footprint',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='footprint',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='footprint',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='part',
            name='level',
        ),
        migrations.RemoveField(
            model_name='part',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='part',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='part',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='footprint',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.FootprintCategory'),
        ),
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.PartCategory'),
        ),
        migrations.AlterField(
            model_name='part',
            name='footprint',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Footprint'),
        ),
    ]
