# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170517_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='mataparts',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='api.Part'),
        ),
    ]
