# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170602_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partparameter',
            old_name='max_exponent',
            new_name='max_prefix',
        ),
        migrations.RenameField(
            model_name='partparameter',
            old_name='min_exponent',
            new_name='min_prefix',
        ),
        migrations.RenameField(
            model_name='partparameter',
            old_name='nom_exponent',
            new_name='nom_prefix',
        ),
    ]
