# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_partdistributor_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='distributor',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='distributor',
            name='email',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='distributor',
            name='phone',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='distributor',
            name='sku_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='distributor',
            name='website',
            field=models.TextField(blank=True, default=''),
        ),
    ]
