# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170518_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='metapartpart',
            name='metapart',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='metapart', to='api.Part'),
        ),
        migrations.AlterField(
            model_name='metapartpart',
            name='part',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='part', to='api.Part'),
        ),
    ]
