# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170605_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partdistributor',
            name='currency',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partdistributor',
            name='sku',
            field=models.TextField(blank=True),
        ),
    ]
