# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170520_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metapart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.PartCategory')),
                ('footprint', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Footprint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Octopart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.PartCategory')),
                ('footprint', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Footprint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='metapartpart',
            name='metapart',
        ),
        migrations.RemoveField(
            model_name='metapartpart',
            name='part',
        ),
        migrations.RemoveField(
            model_name='part',
            name='type',
        ),
        migrations.DeleteModel(
            name='MetapartPart',
        ),
        migrations.AddField(
            model_name='metapart',
            name='parts',
            field=models.ManyToManyField(to='api.Part'),
        ),
    ]
