# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170521_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metapart',
            name='category',
        ),
        migrations.RemoveField(
            model_name='metapart',
            name='footprint',
        ),
        migrations.RemoveField(
            model_name='metapart',
            name='parts',
        ),
        migrations.RemoveField(
            model_name='octopart',
            name='category',
        ),
        migrations.RemoveField(
            model_name='octopart',
            name='footprint',
        ),
        migrations.AddField(
            model_name='part',
            name='parts',
            field=models.ManyToManyField(to='api.Part'),
        ),
        migrations.DeleteModel(
            name='Metapart',
        ),
        migrations.DeleteModel(
            name='Octopart',
        ),
    ]
