# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170522_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='parts',
            field=models.ManyToManyField(blank=True, to='api.Part'),
        ),
    ]
