# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170524_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='footprint',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
