# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_footprint_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('suffix', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('uuid', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PartParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('numeric', models.BooleanField()),
                ('text_value', models.TextField(blank=True, null=True)),
                ('min_value', models.FloatField(null=True)),
                ('nom_value', models.FloatField(null=True)),
                ('max_value', models.FloatField(null=True)),
                ('max_exponent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='max', to='api.Exponent')),
                ('min_exponent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='min', to='api.Exponent')),
                ('nom_exponent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nom', to='api.Exponent')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='partparameter',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Unit'),
        ),
    ]
