# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170612_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footprint',
            name='footprint',
            field=models.FileField(null=True, upload_to='footprints/%y/%m/%d/%H%M/'),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%y/%m/%d/%H%M/'),
        ),
    ]
