# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20170708_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partparameter',
            name='part',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='api.Part'),
        ),
    ]
