# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20170712_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartStockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('amount', models.IntegerField()),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.StorageLocation')),
                ('part', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Part')),
            ],
        ),
    ]
