# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_partstockhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='email',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='phone',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='sku_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='website',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='email',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='phone',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='website',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
