# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20170718_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='filename',
            new_name='source_name',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='uuid',
            new_name='storage_path',
        ),
    ]
