# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-27 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20170721_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='authorized',
            field=models.BooleanField(default=True),
        ),
    ]
