# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-27 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_distributor_authorized'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributor',
            old_name='authorized',
            new_name='allowed',
        ),
    ]
