# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20170727_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Model'),
        ),
    ]
