# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-10 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_part_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StorageLocation',
            new_name='Storage',
        ),
    ]
