# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-19 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20170813_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartAttachement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='partattachement',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.File'),
        ),
        migrations.AddField(
            model_name='partattachement',
            name='part',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attachements', to='api.Part'),
        ),
    ]
