# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_part_octopart_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='footprint',
            name='snapeda_uid',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='footprint',
            name='updated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='snapeda_uid',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='updated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
