# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-27 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20171227_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionedfilehistory',
            name='storage_path',
            field=models.TextField(default=''),
        ),
    ]
