# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-28 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20180116_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionedfile',
            name='category',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
