# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-17 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_versionedfile_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('comment', models.TextField(blank=True, default='')),
                ('snapeda', models.TextField(blank=True, null=True)),
                ('snapeda_uid', models.TextField(blank=True, default=None, null=True)),
                ('updated', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ModelCategory',
            new_name='SymbolCategory',
        ),
        migrations.RemoveField(
            model_name='model',
            name='category',
        ),
        migrations.RemoveField(
            model_name='model',
            name='childs',
        ),
        migrations.RemoveField(
            model_name='model',
            name='image',
        ),
        migrations.RemoveField(
            model_name='model',
            name='model',
        ),
        migrations.RemoveField(
            model_name='part',
            name='model',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.AddField(
            model_name='symbol',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.SymbolCategory'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='childs',
            field=models.ManyToManyField(blank=True, related_name='symbol_childs', to='api.Symbol'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_image', to='api.File'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='symbol',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_file', to='api.File'),
        ),
        migrations.AddField(
            model_name='part',
            name='symbol',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Symbol'),
        ),
    ]
