# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-22 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20180417_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footprint',
            name='category',
        ),
        migrations.RemoveField(
            model_name='footprint',
            name='footprint',
        ),
        migrations.RemoveField(
            model_name='footprint',
            name='image',
        ),
        migrations.RemoveField(
            model_name='footprintcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='category',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='childs',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='image',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='symbolcategory',
            name='parent',
        ),
        migrations.AlterField(
            model_name='part',
            name='footprint',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='footprint', to='api.VersionedFile'),
        ),
        migrations.AlterField(
            model_name='part',
            name='symbol',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='symbol', to='api.VersionedFile'),
        ),
        migrations.DeleteModel(
            name='Footprint',
        ),
        migrations.DeleteModel(
            name='FootprintCategory',
        ),
        migrations.DeleteModel(
            name='Symbol',
        ),
        migrations.DeleteModel(
            name='SymbolCategory',
        ),
    ]
