# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_part_value_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='value_parameter',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
