# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-23 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20180910_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('name', models.TextField()),
                ('uid', models.TextField()),
                ('updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('part', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='api.Part')),
            ],
        ),
    ]
