# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-23 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_partreference_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='octopart',
        ),
        migrations.RemoveField(
            model_name='part',
            name='octopart_uid',
        ),
        migrations.RemoveField(
            model_name='part',
            name='updated',
        ),
    ]
