# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-23 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20181223_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='partparameter',
            name='from_reference',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_reference', to='api.PartReference'),
        ),
    ]
