# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_partreference_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='partreference',
            name='manufacturer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='partreference',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
