# coding: utf-8

"""
    Kipartman

    Kipartman api specifications

    OpenAPI spec version: 1.0.0
    Contact: --
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PartParameterDescription(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'unit': 'Unit',
        'numeric': 'bool'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'unit': 'unit',
        'numeric': 'numeric'
    }

    def __init__(self, name=None, description=None, unit=None, numeric=None):
        """
        PartParameterDescription - a model defined in Swagger
        """

        self._name = None
        self._description = None
        self._unit = None
        self._numeric = None

        if name is not None:
          self.name = name
        if description is not None:
          self.description = description
        if unit is not None:
          self.unit = unit
        if numeric is not None:
          self.numeric = numeric

    @property
    def name(self):
        """
        Gets the name of this PartParameterDescription.

        :return: The name of this PartParameterDescription.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this PartParameterDescription.

        :param name: The name of this PartParameterDescription.
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """
        Gets the description of this PartParameterDescription.

        :return: The description of this PartParameterDescription.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this PartParameterDescription.

        :param description: The description of this PartParameterDescription.
        :type: str
        """

        self._description = description

    @property
    def unit(self):
        """
        Gets the unit of this PartParameterDescription.

        :return: The unit of this PartParameterDescription.
        :rtype: Unit
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """
        Sets the unit of this PartParameterDescription.

        :param unit: The unit of this PartParameterDescription.
        :type: Unit
        """

        self._unit = unit

    @property
    def numeric(self):
        """
        Gets the numeric of this PartParameterDescription.

        :return: The numeric of this PartParameterDescription.
        :rtype: bool
        """
        return self._numeric

    @numeric.setter
    def numeric(self, numeric):
        """
        Sets the numeric of this PartParameterDescription.

        :param numeric: The numeric of this PartParameterDescription.
        :type: bool
        """

        self._numeric = numeric

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PartParameterDescription):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
