# coding: utf-8

"""
    Kipartman

    Kipartman api specifications

    OpenAPI spec version: 1.0.0
    Contact: --
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Storage(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'comment': 'str',
        'id': 'int',
        'category': 'StorageCategory'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'comment': 'comment',
        'id': 'id',
        'category': 'category'
    }

    def __init__(self, name=None, description=None, comment=None, id=None, category=None):
        """
        Storage - a model defined in Swagger
        """

        self._name = None
        self._description = None
        self._comment = None
        self._id = None
        self._category = None

        if name is not None:
          self.name = name
        if description is not None:
          self.description = description
        if comment is not None:
          self.comment = comment
        self.id = id
        if category is not None:
          self.category = category

    @property
    def name(self):
        """
        Gets the name of this Storage.

        :return: The name of this Storage.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Storage.

        :param name: The name of this Storage.
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """
        Gets the description of this Storage.

        :return: The description of this Storage.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this Storage.

        :param description: The description of this Storage.
        :type: str
        """

        self._description = description

    @property
    def comment(self):
        """
        Gets the comment of this Storage.

        :return: The comment of this Storage.
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """
        Sets the comment of this Storage.

        :param comment: The comment of this Storage.
        :type: str
        """

        self._comment = comment

    @property
    def id(self):
        """
        Gets the id of this Storage.

        :return: The id of this Storage.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Storage.

        :param id: The id of this Storage.
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def category(self):
        """
        Gets the category of this Storage.

        :return: The category of this Storage.
        :rtype: StorageCategory
        """
        return self._category

    @category.setter
    def category(self, category):
        """
        Sets the category of this Storage.

        :param category: The category of this Storage.
        :type: StorageCategory
        """

        self._category = category

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Storage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
